### ISSUE TITLE
Code style question

### ISSUE THREAD

**Issue by yan-kisen** [GrabarzUndPartner/nuxt-page-generator-helper#138]
Cool project.

Static Site Generation is still a fairly fresh topic for me. Reading through this repository has given me a lot to think about, so thanks for that. 

----

I don't understand the following line:

https://github.com/GrabarzUndPartner/nuxt-page-generator-helper/blob/6139c00b96a6d4e2e8cd8865794100e667feb960/lib/utils/template.js#L33

What's the purpose of `${['PageExtend'].join(',')}` ?

Why not just the string `'PageExtend'` ?

**Comment by ThornWalli** [comment]
Hi,
I see, this seems to be still something from the history. Was once the idea to specify multiple extends.

Normally `template = template.replace('/* PLACEHOLDER_EXTENDS */', 'extends: PageExtend,')` should be enough :)

Would clean up the line.
